table:
  name: users
  schema: public
array_relationships:
  - name: todos
    using:
      foreign_key_constraint_on:
        column: user_id
        table:
          name: todos
          schema: public
select_permissions:
  - role: user
    permission:
      columns:
        - created_at
        - id
        - last_seen
        - name
      filter: {}
event_triggers:
  - name: sample
    definition:
      delete:
        columns: '*'
      enable_manual: false
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook: http://localhost:8080/v1/graphql
    request_transform:
      body:
        action: remove
      method: POST
      query_params: {}
      template_engine: Kriti
      version: 2
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
